name: CI

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: Cache Node.js modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
                  key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-node-
                      ${{ runner.OS }}-
            - name: Install Packages
              run: npm ci
            - name: Validate Current Configuration (deneb-config.json)
              run: npm run validate-config-for-commit
            - name: Linting Checks
              run: npm run eslint
            - name: Prettier Checks
              run: npm run prettier-check
            - name: Unit Tests
              run: npm test
            - name: Confirm pbiviz package (AppSource Version)
              run: npm run package
            # When pushing to 'next', this will invoke an alpha build
            - name: Alpha Channel Build Check
              if: github.ref == 'refs/heads/next'
              run: |
                  echo "alpha_build=true" >> $GITHUB_ENV
            - name: 'Alpha Channel Build'
              if: env.alpha_build == 'true'
              run: npm run package-alpha
            - name: 'Publish/Update Alpha Channel Pre-Release'
              if: env.alpha_build == 'true'
              uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  automatic_release_tag: 'alpha'
                  prerelease: true
                  title: 'Alpha Channel: Latest Build'
                  files: |
                      dist/ALPHA*.pbiviz
